services:
  ros-viz:
    environment:
      DRN_GPU_ACCELERATION: software

  px4-sitl:
    environment:
      DRN_GPU_ACCELERATION: software
    volumes:
      - type: bind
        source: ./profiles/x500-lidar/models/lidar_2d_v2/model.sdf
        target: /opt/PX4-Autopilot/Tools/simulation/gz/models/lidar_2d_v2/model.sdf
        read_only: true
