services:
  ros-viz:
    environment:
      DRN_PROFILE: x500-precision-land
      DRN_AIRFRAME: x500
      DRN_PROFILE_CAPABILITIES: precision-landing
      DRN_SIM_MODEL_NAME: x500_mono_cam_down_0
      PX4_GZ_WORLD: aruco

  px4-sitl:
    environment:
      PX4_SIM_MODEL: gz_x500_mono_cam_down
      PX4_GZ_WORLD: aruco
