services:
  ros-viz:
    environment:
      DRN_PROFILE: x500-depth
      DRN_AIRFRAME: x500
      DRN_PROFILE_CAPABILITIES: depth-camera
      DRN_SIM_MODEL_NAME: x500_depth_0

  px4-sitl:
    environment:
      PX4_SIM_MODEL: gz_x500_depth
